# These are supported funding model platforms

github: [WeekendP] # Replace with your GitHub username if you have GitHub Sponsors enabled
# custom: ["https://www.buymeacoffee.com/yourusername"] # Uncomment and replace with your actual link
